import Head from 'next/head'
import styles from '../../styles/Home.module.scss'
import {useRouter} from 'next/router'

export default function Post() {
    const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Post {router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Post {router.query.id}</h1>
      <p>asPath: {router.asPath}</p>
    </div>
  )
}
