import Head from 'next/head'
import styles from '../../styles/Home.module.scss'

export default function Posts() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>Lista de postes</div>
    </div>
  )
}
