import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>DevNews - Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>Olá dev!.</div>
    </div>
  )
}
